### ISSUE TITLE
Clean up stray branches

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#125]
@dmasad -- we have a crap load of stray branches. 
Let's both comb through and delete what is not being used.... some how branches end up hanging out after they are merged or abandoned.  Merged ones should be deleted after the merge. 

Here are a list of the remaining branches -- when all of these have been checked off, then they have been acknowledged a keep or delete.

- [x] remotes/origin/Ascii_Server (@dmasad -- hasn't been updated since 2014)
- [x]  remotes/origin/auto-doc-update (@jackiekazil)
- [x]  remotes/origin/continuous_space.17  See #17 (@dmasad -- is this done in #124 / #126)
- [x]  remotes/origin/dmasad,ticket49   See #49 (@dmasad)
- [x]  remotes/origin/dmasad.ticket51.gridfix   See #51 (@dmasad)
- [x]  remotes/origin/docs_update (@dmasad)
- [x]  remotes/origin/kim.ticket35.model_coroutine  See #35 (@dmasad -- is this done in #124 / #126)
- [x]  remotes/origin/master
- [x]  remotes/origin/serialization.test (@dmasad)

When this list is checked off, then this ticket is closable.

**Comment by dmasad** [comment]
This is done. Only keeping master, and the two branches under active development: docs_update and continuous_space.
