### ISSUE TITLE
Tracking issue: Full integration of Example models

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa#2364]
With the core examples being merged back into Mesa in #2358 and now available in [`examples`](https://github.com/projectmesa/mesa/tree/main/examples) we can now start working our checklist:

- [x] Divide models in stable/basic and experimental/advanced models
- [x] Create two folders in Mesa examples: `examples/basic` and `examples/advanced`
- [x] Move over those 9 examples from mesa-examples, retaining git history.
- [ ] Update the examples, to:
   - [ ] Use a standard structure: `agents.py`, model.py and `app.py`
   - [ ] Use the latest features and be implemented elegantly
   - [ ] Use the latest visualisation
- [ ] Include them in Read the Docs (like currently on the [EMAworkbench](https://emaworkbench.readthedocs.io/en/latest/examples.html))
- [ ] Update all other docs and readmes to point towards the new location
- [ ] Integrate the benchmarks models in them and run benchmarks on them.
- [ ] Update the tests to run continuous testing
- [ ] Add visualisation testing
- [ ] We add batch_run testing

Put your name behind something if you want to pick it up!

**Comment by quaquel** [comment]
I'll pick up the read the docs stuff as discussed today.

**Comment by EwoutH** [comment]
@quaquel Awesome! #2365 structures all basic example models to have a flat structure and at least `agents.py` and `model.py`, I think that should help.

**Comment by EwoutH** [comment]
- The moved examples are removed from mesa-examples: https://github.com/projectmesa/mesa-examples/pull/225
- The basic examples have had an extensive update: https://github.com/projectmesa/mesa/pull/2365

I'm going to focus on my thesis for a few days, but happy to review anything!

**Comment by Corvince** [comment]
Just a heads-up that this broke the docs build for the visualization tutorial, because mesa-examples does no longer provide the BoltzmannWealthModel. The vis tutorial does need a larger update anyways (which I somewhere agreed to do), but still this is a major breaking change that we need to communicate somehow. 

Or maybe easier is to provide the same "model export" in core mesa and then just re-export that from mesa-examples. Thats probably the better path now that I think of it. I'll add "make examples importable" to the checklist

**Comment by Corvince** [comment]
> [ ] Discuss enabling ruff and/or ruff-format on (parts of) the examples (in [`pyproject.toml`](https://github.com/projectmesa/mesa/blob/b42e2729e83e11f0d0a3a6d58987fddec1df8fbf/pyproject.toml#L100)).

Curious as to why this needs a discussion? I am strongly in favor of enabling it. Whats a reason against it?

**Comment by EwoutH** [comment]
> Just a heads-up that this broke the docs build for the visualization tutorial, because mesa-examples does no longer provide the BoltzmannWealthModel.

I just noticed it also. That's just an question of updating the path to import from `mesa/examples/basic`, right?

> Curious as to why this needs a discussion? I am strongly in favor of enabling it. Whats a reason against it?

Against: It's a lot of work ;). I made an start in https://github.com/projectmesa/mesa/pull/2370. Docstring we should consider if we want to add and require that everywhere.

**Comment by quaquel** [comment]
I agree its some work but not as bad as what I did a few weeks back with the docstrings. With @Corvince, I believe that we should just enable it and fix all issues. The examples should exemplify good practices.

**Comment by Corvince** [comment]
Not sure, I checked and experimented briefly. There is an extensive hatch documentation about file selection
https://hatch.pypa.io/latest/config/build/#file-selection

From skimming it might be possible from examples, but I don't know if it can automatically be included as "mesa.examples". Someone should figure this out

**Comment by EwoutH** [comment]
@quaquel if you can find the time, having the examples sorted by Basic and Advanced would be really useful, as well as having the [Readme descriptions](https://github.com/projectmesa/mesa/blob/main/mesa/examples/README.md) integrated.

I'm good with making that whole Readme the starting page for https://mesa.readthedocs.io/latest/examples.html, even if it then looks less good on GitHub (or the links only work on Readthedocs, etc.). Renaming headers etc. is also okay.

![image](https://github.com/user-attachments/assets/417e45d0-54d5-4152-95a8-c0783eafb43b)

**Comment by quaquel** [comment]
The example level readme is already included. I hope to find some time this weekend to do the overview of examples readme.
