### ISSUE TITLE
Tracking issue: Stabilizing the Cell Space

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa#2519]
A tracking issue for stabilizing the experimental [Cell Space](https://github.com/projectmesa/mesa/tree/main/mesa/experimental/cell_space).

### Mesa 3.0
A lot of active development, including:

- [x] https://github.com/projectmesa/mesa/pull/2292
- [x] https://github.com/projectmesa/mesa/pull/2296
- [x] https://github.com/projectmesa/mesa/pull/2309
- [x] https://github.com/projectmesa/mesa/pull/2319
- [x] https://github.com/projectmesa/mesa/pull/2333
- [x] https://github.com/projectmesa/mesa/pull/2386

Current spaces
- [x] https://github.com/projectmesa/mesa/pull/2420

### Mesa 3.1
Integration and documentation.

- [ ] https://github.com/projectmesa/mesa/pull/2512
- [ ] Add full and complete docstring
  - [ ] Module-level
  - [ ] Classes
  - [ ] Methods

Current spaces
- [ ] Add [PendingDeprecationWarning](https://docs.python.org/3/library/exceptions.html#PendingDeprecationWarning)

### Mesa 3.2
Stabilizing release
- [ ] Integrate ContinuousSpace
- [ ] Refine visualisation
- [ ] Update tutorial
- [ ] Switch over basic example models
- [ ] Write migration guide

Current spaces
- [ ] Switch to [DeprecationWarning](https://docs.python.org/3/library/exceptions.html#PendingDeprecationWarning)

### Mesa 4.0
- [ ] Make new (optionally breaking) changes to Cell Space
- [ ] Remove current spaces
- [ ] Rename to "space"?

Everyone let me know what you think, especially @quaquel and @Corvince.

**Comment by Souvik9205** [comment]
Hi, I would like to work on this issue

**Comment by EwoutH** [comment]
Great! You can see what’s still TODO, feel free to pick one and start working on it.

**Comment by quaquel** [comment]
@EwoutH, do we want to move over the basic examples as part of 3.2, or as part of 3.3?

Personally, it would make more sense to do it for 3.2.

**Comment by EwoutH** [comment]
I’m also good with 3.2, like the tracking issue currently states.

The big ticket item is integrating the Continuous Space, so we can keep a unified concept of space.

**Comment by quaquel** [comment]
> The big ticket item is integrating the Continuous Space, so we can keep a unified concept of space.

sounds like a fun thing for me to work on over the christmas break. In the mean time, I'll continue updating various examples to use all the new stuff that came in 3.1.

**Comment by EwoutH** [comment]
Actually, I might be interested to do some exploratory work on this over the weekend, as an integrated effort on integrating (parts of) Mesa-Geo.

**Comment by EwoutH** [comment]
Now that we want to stabilize the the cell space, we have to think about the namespace or module name we're going to put it in.

Since it also contains a continuous component, I don't think `cell_space` is the perfect description anymore. We could simply put it in a `space` namespace (folder) and let the `space` module exists as is. That could introduce naming conflicts, so we could also name it `new_space` before 4.0, and than with 4.0 make it simply `space` again.

**Comment by quaquel** [comment]
> Since it also contains a continuous component, 

Cell-spaces/discrete spaces and continuous spaces are really different things, so I would counsel against collapsing them. Conceptually, the underlying maths, for example, is quite distinct. Implementation-wise and API-wise, they are also quite different. I want to explore the possibility of having a generic space protocol to improve API alignment, but I don't see a feasible or desirable path beyond that. 

So, I prefer `mesa.discrete_space` and `mesa.continuous_space` as folders while we leave the existing `mesa.space` file with a deprecation warning. I prefer folders over a single file because of the ease of finding stuff. From a user side, it does not matter as long as the relevant stuff is just importable from the right namespace.

**Comment by EwoutH** [comment]
Sounds logical. Maybe we can even do `mesa.space.discrete` and `.continuous`.

**Comment by quaquel** [comment]
not sure: flat is better than nested.

**Comment by EwoutH** [comment]
Two open issues that sould be tackled:

- [ ] Update tutorial (further)
- [ ] Write a part in the [migration guide](https://github.com/projectmesa/mesa/blob/main/docs/migration_guide.md)
